import inspect
from enum import Enum


class ChoiceEnum(Enum):
    ''' Simplify all choice enum const classes declaration. Autogenerated choices tuple'''
    @classmethod
    def choices(cls):
        # get all members of the class
        members = inspect.getmembers(cls, lambda m: not(inspect.isroutine(m)))
        # filter down to just properties
        props = [m for m in members if not(m[0][:2] == '__')]
        # format into django choice tuple
        choices = tuple([(p[1].value, p[0]) for p in props])
        return choices


class NotificationTypes(ChoiceEnum):
    EVENT_INVITE = 1
    EVENT_UPDATE = 3
    EVENT_CANCEL = 6
    EVENTGUEST_RSVP = 2
    ALBUMFILE_UPLOAD = 4
    ACCOUNT_EMAIL_VALIDATE = 5


class CalendarTypes(ChoiceEnum):
    WORK_CALENDAR = 1
    PERSONAL_CALENDAR = 2


class EventStatus(ChoiceEnum):
    DRAFT = 1
    ACTIVE = 2
    CANCELLED = 3
